### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by abulka** [chaitanya11/grapesjs-plugin-button-event#1]
I've included the plugin in my project but not sure how to benefit from it - could you please share an example?
Clicking on the snowflake icon gives me
```
gjs-sampleButtonEvent
emited gjs-sampleButtonEvent event
```

This plugin is not listed as an [official plugin](https://github.com/artf/grapesjs#plugins) so perhaps I've just stumbled on an abandoned prototype of a plugin? I thought perhaps I might be able to send events between components using this plugin, rather than scripting by hand.

**Comment by chaitanya11** [comment]
Hi @abulka this plugin is only developed as part of BodylessCMS. This is not intended to be an official plugin for grapesjs. It is not abandoned plugin or something just it's purpose is different. If you want to see an example of how to integrate this plugin please refer to BodylessCMS code.
https://github.com/chaitanya11/BodylessCMS
